import type { Metadata } from 'next';
import './globals.css';

import { silkscreen, satoshi, gohu } from '@/fonts/font';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${silkscreen.variable} ${satoshi.variable} ${gohu.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
